spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: liushan
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver